# Generated by Django 4.1.1 on 2022-09-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='pw',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
